// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY59B8aC8gIzi2ioK4sO7WqK3zKRma6N8',
    appId: '1:774679324926:web:6141ce3522825ebf881daf',
    messagingSenderId: '774679324926',
    projectId: 'task-management-app-e7375',
    authDomain: 'task-management-app-e7375.firebaseapp.com',
    storageBucket: 'task-management-app-e7375.firebasestorage.app',
    measurementId: 'G-D0W6RBLSP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrCA-W73Ko3DoMUQWmSJ4VNGQfGm1ONr4',
    appId: '1:774679324926:android:b84f7fb21be0fbf5881daf',
    messagingSenderId: '774679324926',
    projectId: 'task-management-app-e7375',
    storageBucket: 'task-management-app-e7375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_2tK3OUxZtdf2EaUVkCOiU37bAK6JbvY',
    appId: '1:774679324926:ios:e15b300c57fdc6f2881daf',
    messagingSenderId: '774679324926',
    projectId: 'task-management-app-e7375',
    storageBucket: 'task-management-app-e7375.firebasestorage.app',
    iosBundleId: 'com.example.taskproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_2tK3OUxZtdf2EaUVkCOiU37bAK6JbvY',
    appId: '1:774679324926:ios:e15b300c57fdc6f2881daf',
    messagingSenderId: '774679324926',
    projectId: 'task-management-app-e7375',
    storageBucket: 'task-management-app-e7375.firebasestorage.app',
    iosBundleId: 'com.example.taskproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY59B8aC8gIzi2ioK4sO7WqK3zKRma6N8',
    appId: '1:774679324926:web:96f705ab52e0fb15881daf',
    messagingSenderId: '774679324926',
    projectId: 'task-management-app-e7375',
    authDomain: 'task-management-app-e7375.firebaseapp.com',
    storageBucket: 'task-management-app-e7375.firebasestorage.app',
    measurementId: 'G-S3NXMXQG9Z',
  );
}
